# Generated by Django 4.2.17 on 2024-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_location', models.CharField(max_length=255)),
                ('price_night_in_dollar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_rooms', models.IntegerField()),
                ('images_1', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('images_2', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('images_3', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
            ],
        ),
    ]
