# Generated by Django 4.2.17 on 2024-12-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryBusyroomsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usermodel')),
            ],
            options={
                'unique_together': {('user', 'hotel', 'room_number', 'check_in', 'check_out')},
            },
        ),
    ]
