# Generated by Django 4.2.17 on 2024-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_temporarybusyroomsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='tg_user',
            field=models.FloatField(default=False, null=True),
        ),
    ]
