# Generated by Django 4.2.17 on 2024-12-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_usermodel_tg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='tg_user',
        ),
    ]
