# Generated by Django 4.2.17 on 2024-12-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_usermodel_tg_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usermodel')),
            ],
        ),
    ]
